### ISSUE TITLE
wrong detection of avif images

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-mediahandler#148]
**Description**
avif images are detected as mp4 but then fail:

```
[ 2] Error detecting dimensions: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds video/mp4
[ 2] Error to convert to png AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'video/mp4'
- 'image/avif'
    at avif2png (file:///Users/tripod/codez/helix/helix-md2docx/test/md2docx.test.js:75:10)
    at file:///Users/tripod/codez/helix/helix-md2docx/src/mdast2docx/mdast-download-images.js:126:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

see test image: 
https://github.com/adobe/helix-md2docx/blob/0a6b7034ca9118016a24197647d49835cddad83d/test/fixtures/test-300.avif

**Comment by tripodsan** [comment]
i was mistaken
